global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  width: 20.0
  height: 20.0 

  update_frequency: 15.0
  publish_frequency: 15.0
  transform_tolerance: 0.5

  static_map: true

  plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  
