global_costmap:
  global_frame: map
  robot_base_frame: base_link

  # width: 300.0
  # height: 300.0 

  update_frequency: 8.0
  publish_frequency: 8.0
  transform_tolerance: 0.5

  static_map: true

  plugins:
  - {name: static_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
  - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  
static_layer:
  map_topic: "/map"           # Ensures it subscribes to the map_server's topic
  subscribe_to_updates: true  # Allows dynamic updates to the map