local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 8.0
  publish_frequency: 5.0
  transform_tolerance: 0.5  

  static_map: false
  rolling_window: true  # Ensures the local costmap moves with the robot
  width: 6.0            # Increased width for better obstacle awareness
  height: 6.0           # Increased height for better obstacle awareness
  resolution: 0.05      # Suitable resolution for indoor environments

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}