shutdown_costmaps: true
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behavior_enabled: true

rotate_recovery:
  max_rotational_vel: 0.5   # Lower rotational velocity
  min_rotational_vel: 0.1   # Minimum rotational velocity
  yaw_goal_tolerance: 0.1   # Set a larger tolerance to stop spinning sooner